services:
  - type: web
    name: stm-discord-bot
    env: node
    plan: free
    branch: main

    buildCommand: npm install && npm run build
    startCommand: node dist/index.js

    autoDeploy: true
